### ISSUE TITLE
Updating newrelic DataPartitionRuleConfiguration api

### ISSUE THREAD

**Issue by eknuth** [resmoio/documentation#2]
Hello @serhatcan! 

We are adding new capabilities to New Relic's logging product data partition rules. We are deprecating and will eventually replace the `matchingCriteria` field with a new field named `nrql` which can express all of the existing functionality and even more.

We intend to deploy a change that will make the `matchingCriteria` nullable and expose the new `nrql` field. This should not change any of the existing functionality and your existing integrations should still function as before.  However new data partition rules that are created with the `nrql` field can express functionality that cannot be destructured into `matchingCriteria`. In that case `matchingCriteria` will be null and could cause issues with your current integration.

The existing `matchingCriteria` and sub fields are all encapsulated in the new `nrql` field.  However the existing `matchingCriteria` field will be deprecated we eventually intend to remove it. Please let us know if you have any concerns or comments.  Thank you!

<img width="1413" alt="image" src="https://user-images.githubusercontent.com/200663/216714183-9f62a766-a67a-4951-b16a-c9123a9908e5.png">

**Comment by serhatcan** [comment]
Just opened an issue for this thank you!

**Comment by eknuth** [comment]
Thanks! Here is the update to our docs site with more information. 

https://github.com/newrelic/docs-website/pull/11385

**Comment by shuetisha** [comment]
Hi @eknuth,

We made the required changes on our side. Currently, we define `matchingCriteria` field as a nullable field when it's deprecated on your production we will delete it and continue with `nrql` field. Thanks for the heads up!
